siteTitle = "Guillaume Haben"
siteDescr = "In this world since 22 winters. Engineering student at TELECOM Nancy. Design & web lover."
siteAuthor = "Guillaume Haben"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/GuillaumeHaben"
siteGithubUrl = "https://github.com/GuillaumeHaben"
siteEmailUrl = "mailto:haben.guillaume@me.com"
siteLinkedinUrl = "https://www.linkedin.com/in/guillaumehaben"
siteRssUrl = "#"
siteVkUrl = "#"

linkPrefix = "/"
